name: HealthChain
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Adjusted for broader compatibility

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  curved_navigation_bar: ^1.0.3
  socket_io_client: ^2.0.3+1
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/healththehain_logo.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/icons/accueil.png
    - assets/icons/document.png
    - assets/icons/calendrier.png
    - assets/icons/bulle.png
    - assets/icons/utilisateur.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/healththehain_logo.png"
  min_sdk_android: 21 # Optional: Adjust if needed